redis:
  image: redis
  ports:
    - "6379"

web:
  restart: always
  build: ./backend
  expose:
    - "8000"
  env_file: .backend-env-dev
  links:
    - redis:redis
  command: /usr/local/bin/gunicorn -w 4 -b :8000 app.wsgi:app

static:
  build: ./frontend
  command: cp -a /placeholder/. /var/www/static/

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - static
  links:
    - web:web
